version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]
  exclude_patterns = ['tests/**']

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"
